title: Active Personas

description: Active Personas (APs), fictional users capable of generating contextual feedback through an interactive multi-modal interaction, such as text, voice, image, and video. APs enable development teams to gather feedback on their solutions through iterative internal experimentation. APs use generative artificial intelligence to enable dynamic multi-modal interaction and utilize user personas to generate contextual feedback.

theme: just-the-docs

url: https://active-personas.github.io

baseurl: ""

favicon_ico: "/assets/favicon.ico"

logo: "/assets/active-personas-logo-long.svg"

repository: active-personas/active-personas.github.io

enable_copy_code_button: true

nav_enabled: true

back_to_top: true

back_to_top_text: "Back to top"

aux_links:
  GitHub Repository: https://github.com/active-personas/active-personas.github.io

plugins:
  - jekyll-default-layout
  - jekyll_img
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
